spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication_system
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostreSLDialect

  mail:
    host: localhost
    port: 1025
    username: amjed
    password: amjed
    properties:
      mail:
        smtp:
          trust: "*"e
        auth: true
        starttls:
          enable: truee
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
